### ISSUE TITLE
Error message during shelr push last

### ISSUE THREAD

**Issue by sseering** [shelr/shelr#21]
I get the following error message when running shelr push last (no tags, no API key):

```
=> Something went wrong...
757: unexpected token at '<!DOCTYPE html>
<html>
    <head>
        <meta charset='utf-8'/>
        <link href='http://fonts.googleapis.com/css?family=Inconsolata' rel='stylesheet' type='text/css'>
        <style type="text/css">
            body {
                color: white;
                background-color: black;
            }
            .cursor {
                -moz-animation-name: blink;
                -moz-animation-duration: 1.5s;
                -moz-animation-iteration-count: infinite;
                -moz-animation-timing-function: cubic-bezier(1,0,0,1);
            }
            html, body, #wrapper {
                height:100%;
                margin: 0;
                padding: 0;
                border: none;
                text-align: center;
                font-size: 24pt;
                font-family: 'Inconsolata',monospace;
                font-weight: normal;
            }
            #wrapper {
                margin: 0 auto;
                text-align: left;
                vertical-align: middle;
            }
            .cow {
                font-family: 'Inconsolata',monospace;
                font-size: 24pt;
            }
            .description {
                border-right: .5em solid;
                border-right: 1ch solid;
                width: 9em;
                width: 18ch;
                white-space: nowrap;
                overflow: hidden;
                   -moz-animation: typing 3s steps(18, end), blink-caret 1s cubic-bezier(1,0,0,1) infinite alternate;
                -webkit-animation: typing 3s steps(18, end), blink-caret 1s cubic-bezier(1,0,0,1) infinite alternate;
                     -o-animation: typing 3s steps(18, end), blink-caret 1s cubic-bezier(1,0,0,1) infinite alternate;
                        animation: typing 3s steps(18, end), blink-caret 1s cubic-bezier(1,0,0,1) infinite alternate;
            }
               @-moz-keyframes typing { from { width: 0; } }
            @-webkit-keyframes typing { from { width: 0; } }
                 @-o-keyframes typing { from { width: 0; } }
                    @keyframes typing { from { width: 0; } }
               @-moz-keyframes blink-caret { 50% { border-color: transparent; } }
            @-webkit-keyframes blink-caret { 50% { border-color: transparent; } }
                 @-o-keyframes blink-caret { 50% { border-color: transparent; } }
                    @keyframes blink-caret { 50% { border-color: transparent; } }
        </style>
    </head>
    <body>
        <table id="wrapper">
            <tr>
                <td>
<pre class="cow">
 ___________________________ 
&lt; 500 Internal Server Error &gt;
 --------------------------- 
        \   ^__^
         \  (xx)\_______
            (__)\       )\/\
             U  ||----w |
                ||     ||

</pre>
                <div class="description">Our fault. Sorry:(</div>
            </tr>
        </table>
    </body>
</html>
'
/usr/lib/ruby/2.0.0/json/common.rb:155:in `parse'
/usr/lib/ruby/2.0.0/json/common.rb:155:in `parse'
/usr/lib/ruby/gems/2.0.0/gems/shelr-0.16.3/lib/shelr/publisher.rb:50:in `block in handle_response'
/usr/lib/ruby/gems/2.0.0/gems/shelr-0.16.3/lib/shelr/publisher.rb:41:in `with_exception_handler'
/usr/lib/ruby/gems/2.0.0/gems/shelr-0.16.3/lib/shelr/publisher.rb:49:in `handle_response'
/usr/lib/ruby/gems/2.0.0/gems/shelr-0.16.3/lib/shelr/publisher.rb:14:in `block in publish'
/usr/lib/ruby/gems/2.0.0/gems/shelr-0.16.3/lib/shelr/publisher.rb:41:in `with_exception_handler'
/usr/lib/ruby/gems/2.0.0/gems/shelr-0.16.3/lib/shelr/publisher.rb:10:in `publish'
/usr/lib/ruby/gems/2.0.0/gems/shelr-0.16.3/bin/shelr:82:in `<top (required)>'
/usr/bin/shelr:23:in `load'
/usr/bin/shelr:23:in `<main>'
```

**Comment by justbrowsing** [comment]
I have the same error. Also using ruby 2.0 and shelr 0.16.3 on ArchLinux. Doesn't seem to build using ruby 1.8 either.

EDIT: Apparently those pushes do go through successfully to the server, however the client still displays that error. Also tested with ruby 1.9.3 and shelr 0.16.2 on another machine (used to work without error) same error message.

**Comment by lefred** [comment]
Same issue for me with ruby 2.0.0p247 (2013-06-27 revision 41674) [x86_64-linux] and shelr 0.16.3

This is Fedora 19.

And I confirm that the push occurs anyway.

**Comment by varac** [comment]
same here
