### ISSUE TITLE
shelr dump fails

### ISSUE THREAD

**Issue by varac** [shelr/shelr#25]
```
--- ~ » shelr dump last

Your record will be published under terms of
Creative Commons Attribution-ShareAlike 3.0 Unported
See http://creativecommons.org/licenses/by-sa/3.0/ for details.

Description: test
Tags (ex: howto, linux):   
=> Something went wrong...
"\xC2" on US-ASCII
/usr/lib/ruby/vendor_ruby/shelr/publisher.rb:92:in `encode'
/usr/lib/ruby/vendor_ruby/shelr/publisher.rb:92:in `to_json'
/usr/lib/ruby/vendor_ruby/shelr/publisher.rb:92:in `prepare'
/usr/lib/ruby/vendor_ruby/shelr/publisher.rb:21:in `block (2 levels) in dump'
/usr/lib/ruby/vendor_ruby/shelr/publisher.rb:20:in `open'
/usr/lib/ruby/vendor_ruby/shelr/publisher.rb:20:in `block in dump'
/usr/lib/ruby/vendor_ruby/shelr/publisher.rb:41:in `with_exception_handler'
/usr/lib/ruby/vendor_ruby/shelr/publisher.rb:19:in `dump'
/usr/bin/shelr:71:in `<main>'
```

Any clue how i can fix this ?

**Comment by varac** [comment]
This problem has been fixed by assigning LC_CTYPE="en_US.UTF-8"
